### ISSUE TITLE
add automated checks to lint/style of source documents

### ISSUE THREAD

**Issue by ghost** [riscv/docs-spec-template#17]
This is follow up to this post: https://lists.riscv.org/g/sig-documentation/message/126

I'd be happy to submit a PR for a [pre-commit solution](https://pre-commit.com/index.html)

**Comment by wmat** [comment]
Thanks Kevin, we have plans on the books for this exact thing in 2024 and I greatly appreciate your contributions thus far.  Please monitor to Documentation SIG mailing list for discussions on this topic as we move forward.
