### ISSUE TITLE
provide html output in workflow

### ISSUE THREAD

**Issue by ghost** [riscv/docs-spec-template#18]
This could be as simple as using `asciidoctor`  tool and/or a static site generator like [jekyll](https://jekyllrb.com/) or [antora](https://antora.org/) could be use to provide a more feature rich website.

possible features:

* deploy to github pages
* search
* complex nav (ability to have multi-page, intra-page)
* links
  * edit source
  * file issue

**Comment by wmat** [comment]
Hi Kevin, we have no plan to deploy anything to GH Pages currently.  However, we are planning to launch a feature rich documentation with in 2024, most likely based on Antora.  This plan has been in the works for some time and as we approach closer on conversion of all of the ratified specs to AsciiDoc, a next step will be implenting a Documentation site on riscv.org.

**Comment by ghost** [comment]
Thanks for the explanation on long term strategy for RVI specs.

I'm attaching a PR to this with no expectations that this request go further as it doesn't have any css with it so it renders much different than the pdf version.

I look forward to seeing the doc site repo soon.
