### ISSUE TITLE
move asciidoc src files to src dir; create build dir to build all artifact in

### ISSUE THREAD

**Issue by ghost** [riscv/docs-spec-template#25]
Similar to other specs: 

* https://github.com/riscv-non-isa/riscv-sbi-doc
* https://github.com/riscv/riscv-isa-manual

I think it makes sense to organize the content in the spec in a separate dir, rather than at the top level where it can be harder to find with other content.

I will provide a PR...

**Comment by wmat** [comment]
I'd agree with you.  Can you make sure READMEs instructions note this structure?

**Comment by ghost** [comment]
> I'd agree with you. Can you make sure READMEs instructions note this structure?

Yes, #27
