### ISSUE TITLE
Node 12 Deprecation warnings on Workflows

### ISSUE THREAD

**Issue by jjscheel** [riscv/docs-spec-template#5]
Warnings like the following occurred on during the build-pdf and create-release workflows:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. ...

**Comment by jjscheel** [comment]
The following commits address these issues by updating versions on GitHub actions:
- Update versions to address Node changes: e2564c43fb437dfad2fdacff0fe9306309be45b4
- Update to address Node 12 deprecation: 8a74c70876c31d7692a27c7e820f51ca53f46ec8
- Revert create-release to v1: a160a4ee886384a8c237d3d728b75e8150378d04

This commit addresses the GitHub actions which are read-only (archived) and won't be update by substituting a different action 
- Remove archived WF actions: fdf6097d9971b1b0f5d7e22deba6d97664fd5bfb

**Comment by jjscheel** [comment]
Will leave open as we decide how best to propagate to existing projects.

Note: the [riscv-isa-asciidoc branch of riscv/riscv-isa-manual](https://github.com/riscv/riscv-isa-manual/tree/riscv-isa-asciidoc) contains a PR to address these issues.  No other projects have included at this time.

**Comment by jjscheel** [comment]
These projects have been addressed at this time:
1. risc/riscv-isa-manual (riscv-isa-asciidoc branch only)
2. riscv-non-isa/riscv-ap-tee
3. riscv-non-isa/riscv-iommu
4. riscv/riscv-crypto

**Comment by rpsene** [comment]
This issue is no longer applying to this code since the move to contairners.
