### ISSUE TITLE
compress generated pdf

### ISSUE THREAD

**Issue by jnk0le** [riscv/docs-spec-template#9]
I think it would be good if the riscv adoc documents were as small as the latex ones.
Especially considering the fact that I often approach github repos/releases that download at less than 500kbps.

Currently the adoc unpriv is 8x the size of the latex one.

There is a simple `-a compress` command to put in a makefile, which in my case, yielded 314KiB document out of 1.2MiB. Didn't visibly affect build time.

There are also some external tools that claim to strip more.

**Comment by rpsene** [comment]
@wmat any suggestion here? We are using the compress instruction already.

**Comment by wmat** [comment]
I am looking into optimizing the output.  There is asciidoctor-pdf
extensions such as
https://docs.asciidoctor.org/pdf-converter/latest/optimize-pdf/ that can be
used.  We'll test this out and see how effective it is.

**Comment by rpsene** [comment]
The asciidoc compression parameter is already in place https://github.com/riscv/docs-spec-template/blob/main/Makefile#L26.
